Comingtoamerica landing
spacesvr/muse-place pull request #34
Opened 2021-02-21 12:17 UTC by ianyimi

Landing Page

2021-02-22 08:01 UTC, alex-shortt commented on next-env.d.ts
> +declare module "react-video-js-player";
out of curiosity what is this for?

2021-02-22 08:34 UTC, alex-shortt requested changes
code looking good, mainly needs some organization to make things more readable.

quality assurance checks:
- the x of the popup looks a little ugly
- add an animation to the color change on the ENTER/SCHEDULE/TRAILER buttons
- add a color change to the share buttons
- conditions of use title is clipped at the top
- the x on the conditions popup clashes with the scroll bar
- i think you should make the barbers picture in the background smaller or even a bit transparent on mobile, it clashes quite a bit with the text. 
- missing credits at the bottom of the site, double check the mockup

2021-02-22 08:34 UTC, alex-shortt commented on src/scenes/ComingToAmerica/Landing/components/Content.tsx
> +                {/* eslint-disable-next-line react/no-unescaped-entities */}
store copyright data as template string in separate file, like
assets.ts >
```
export const terms = `asdf...`
```

2021-02-22 08:34 UTC, alex-shortt commented on src/scenes/ComingToAmerica/Landing/components/Content.tsx
> +                {/* eslint-disable-next-line react/no-unescaped-entities */}
or, if you need the html, just export the html
```export const terms = <div>asdf...</div>```

2021-02-22 08:34 UTC, alex-shortt commented on src/scenes/ComingToAmerica/Landing/components/TrailerVideo.tsx
> +            : "1400"
move lengthy logic operations before the return statement to allow components to be readable. also you sure you can't use a variable width variable?

2021-02-22 08:34 UTC, alex-shortt commented on src/scenes/ComingToAmerica/Landing/components/Video.tsx
> +            : "400"
move logic to before return statement

2021-02-22 08:34 UTC, alex-shortt commented on src/scenes/Nick/modifiers/SpringFace.tsx
> +const SpringFace = (props: Props) => {
think this file was accidentally added?

2021-02-22 08:34 UTC, alex-shortt commented on src/scenes/Nick/utils/spring.tsx
> +};
was this file accidentally added?

2021-02-22 08:34 UTC, alex-shortt commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.1.14",
didn't see these get used? it not delete them

2021-02-22 08:34 UTC, alex-shortt commented on src/scenes/ComingToAmerica/Landing/components/Content.tsx
> +            <SurroundingTitle className="top">WELCOME TO THE</SurroundingTitle>
gotta change into different components, too much going on

2021-02-22 08:34 UTC, alex-shortt commented on src/scenes/ComingToAmerica/Landing/components/Content.tsx
> +            >
make into a separate component that conditionally renders with 
```
if(!schedule) return null

return <>...</>
```

2021-02-22 08:34 UTC, alex-shortt commented on src/scenes/ComingToAmerica/Landing/components/Content.tsx
> +    </Page>
these trailing ternary operators are very difficult to read, separate components would make it cleaner

2021-02-22 08:34 UTC, alex-shortt commented on src/scenes/ComingToAmerica/Landing/components/ContentStyles.tsx
> +  background-image: url("${content}/images/C2A_Website_Background_Pop-Up_4.png");
instead of getting a new image (which btw if you are going to use it, should be compressed, see https://squoosh.app/editor), use the same format as the `<Background />` component: tile the pink and overlay on the red/yellow background. this way assets are shared and it should load much quicker

2021-02-22 08:34 UTC, alex-shortt commented on src/scenes/ComingToAmerica/Landing/components/ContentStyles.tsx
> +  background-image: url("${content}/images/AMAZON_ORIGINAL_MOVIE1.png");
compress image, see https://squoosh.app/editor, it's at 3MB right now

2021-02-22 08:34 UTC, alex-shortt commented on src/scenes/ComingToAmerica/Landing/components/Content.tsx
> +              X
the X looks ugly, recommend either using an svg, using fontawesome (make sure to only add the packages and individual icons you need), or a low size image online

2021-02-22 09:11 UTC, ianyimi commented on next-env.d.ts
> +declare module "react-video-js-player";
this was to fix a vercel error i had where it wouldnt find the module. it suggested to add this line on the vercel error and it fixed it

2021-02-22 18:40 UTC, alex-shortt commented
Full mockups that need to be matches "exactly" (per b8) are here: https://www.dropbox.com/sh/9iyrhi1tbka0i45/AAB8V4KOPstrD7MVoASEBckwa?dl=0

2021-02-23 00:28 UTC, alex-shortt commented on src/scenes/ComingToAmerica/Landing/components/Content.tsx
> +              X
nvm match the mockup exactly lmao, lmk if you need the asset i can hit up MODU

2021-02-23 11:08 UTC, alex-shortt requested changes
a few changes

2021-02-23 11:08 UTC, alex-shortt commented on src/scenes/ComingToAmerica/Landing/components/Content.tsx
> +  console.log(document.cookie);
```
if(!localStorage.getItem("c2a-visited")){
  setFirstLogin(true);
  localStorage.setItem("c2a-visited", "visited");
}
```

2021-02-23 11:13 UTC, alex-shortt commented
replace divs with h1/h2/button/p/

2021-02-23 13:36 UTC, alex-shortt approved these changes
wew

2021-02-23 13:36 UTC, merged