Pull Request with 9 sites
spacesvr/muse-place pull request #48
Opened 2021-03-02 01:44 UTC by veltsonbastien

1) My site: veltsonbastien.tsx, where I had to remove Codame 
2) The Ruby For Fun site - which seemed fine, but still wondering if any issues there 
3) 8 sites, two of which had issues because of the usage of MP4's and Alto, and one that had issues because I used other links that wasn't purely a link to a file.

2021-03-02 17:52 UTC, alex-shortt requested changes
just a few things!

2021-03-02 17:52 UTC, alex-shortt commented on src/pages/andrecristofi.tsx
> +const url = `https://d27rt3a60hh1lx.cloudfront.net/content/muse.place/andreacristofi`;
wrong url? images aren't working

2021-03-02 17:52 UTC, alex-shortt commented on src/pages/andrecristofi.tsx
> +        <title>Andrea Cristofi | Muse Place</title>
andre or andrea?

2021-03-02 17:52 UTC, alex-shortt commented on src/pages/selva.tsx
> +      <Standard
if a body isn't passed the default text references a different organization, just pass in empty string or put something vague like "This talented 3D artist shows off his crazy skills!"

2021-03-02 17:52 UTC, alex-shortt commented on src/pages/siimbiieselassiie.tsx
> +        audio="https://d27rt3a60hh1lx.cloudfront.net/audio/ini-bestmixever.mp3"
same as the other issue, you need either an empty body string or something vague

2021-03-02 22:19 UTC, veltsonbastien commented on src/pages/andrecristofi.tsx
> +const url = `https://d27rt3a60hh1lx.cloudfront.net/content/muse.place/andreacristofi`;
My bad, "andre" vs. "andrea"

2021-03-02 22:20 UTC, veltsonbastien commented on src/pages/andrecristofi.tsx
> +        <title>Andrea Cristofi | Muse Place</title>
"andre" sorry- fixed.

2021-03-02 22:22 UTC, veltsonbastien commented on src/pages/selva.tsx
> +      <Standard
Okay I'm assuming you meant to add in a `<Body> some text </Body>` tag just in that format, so that's what I did- please let me know if that's not correct.

2021-03-03 02:57 UTC, veltsonbastien commented on src/pages/siimbiieselassiie.tsx
> +        audio="https://d27rt3a60hh1lx.cloudfront.net/audio/ini-bestmixever.mp3"
It should be fine now.

2021-03-03 02:57 UTC, veltsonbastien commented on src/pages/selva.tsx
> +      <Standard
Should be fine now.

2021-03-03 04:22 UTC, alex-shortt approved these changes

2021-03-03 04:41 UTC, merged