Gotham fixes
spacesvr/muse-place pull request #56
Opened 2021-03-11 09:39 UTC by alex-shortt

- some sites from ben
- onboarding from isaiah
- email collection from alex
- new typeform link to track source

2021-03-11 20:45 UTC, ianyimi requested changes

2021-03-11 20:45 UTC, ianyimi commented on src/scenes/Silks/components/Kiosk/components/Control 2.tsx
> +  // }, [addSVG, cancelSVG, variant, variant?.available]);
comments

2021-03-11 20:45 UTC, ianyimi commented on src/themes/Gotham/models/StructureOpen.tsx
> +        {/*/>*/}
comments

2021-03-12 05:00 UTC, alex-shortt commented on src/themes/Gotham/models/StructureOpen.tsx
> +        {/*/>*/}
I like to leave gltfjsx aspect commented out so we know the structure in case we want to change it later

2021-03-12 05:07 UTC, ianyimi commented on src/themes/Gotham/models/StructureOpen.tsx
> +        {/*/>*/}
k gotchu

2021-03-12 05:08 UTC, ianyimi approved these changes

2021-03-12 05:08 UTC, merged