Templatedsites + kiraSites
spacesvr/muse-place pull request #58
Opened 2021-03-13 23:32 UTC by ianyimi

2021-03-13 23:59 UTC, alex-shortt requested changes
- please fill out the pr description a little
- remove assets folder, assets should be on s3
- seems like you should be able to use the kira scene to add lighting if that's the main thing

2021-03-13 23:59 UTC, alex-shortt commented on src/pages/kirax23/alto.tsx
> +import { ScrollData } from "../../themes/Alto/types/scroll";
dont need `../../`, just `themes/`

2021-03-13 23:59 UTC, alex-shortt commented on src/pages/kirax23/index.tsx
> +import { GothamProps } from "../../themes/Gotham";
dont need ../../, just themes/

2021-03-13 23:59 UTC, alex-shortt commented on src/themes/Alto/models/AltoModel.tsx
> +  // );
comments

2021-03-13 23:59 UTC, alex-shortt commented on src/scenes/Alto/index.tsx
> +import Video from "spacesvr";
bad import

2021-03-13 23:59 UTC, alex-shortt commented on src/themes/Alto/components/Scrolls/Scroll.tsx
> +import { useLimiter } from "../../../../scenes/Silks/utils/limiter";
import from spacesvr

2021-03-13 23:59 UTC, alex-shortt commented on src/themes/Alto/kira.tsx
> +        <Grass />
why do you need this file? looks the same as the standard alto

2021-03-13 23:59 UTC, alex-shortt commented on src/themes/Alto/components/Scrolls/Scroll.tsx
> +      if (inRange) {
&&?

2021-03-13 23:59 UTC, alex-shortt commented on src/scenes/Gotham/OldGotham.tsx
> +      <Lighting color={lightColor} />
seems like the only thing this audio adds is dual environment and lighting. if thats the case it should be a scene. in fact we already have a kira scene, think you should be able to edit that

2021-03-14 00:12 UTC, ianyimi commented on src/scenes/Gotham/OldGotham.tsx
> +      <Lighting color={lightColor} />
it also removes the buidings and adds the outside mesh with the heightmap and gradient applied

2021-03-14 00:19 UTC, ianyimi commented on src/themes/Alto/kira.tsx
> +        <Grass />
it doesnt have the sun or the fog for the hdri thats the only diff

2021-03-14 00:39 UTC, alex-shortt requested changes
small thing then good

2021-03-14 00:39 UTC, alex-shortt commented on src/pages/kirax23/alto.tsx
> +const Standard = dynamic(import("scenes/Alto/kira"), { ssr: false });
scenes should have a capital, Kira

2021-03-14 00:39 UTC, alex-shortt commented on src/themes/Alto/kira.tsx
> +
capital K for Kira

2021-03-14 00:47 UTC, alex-shortt approved these changes

2021-03-14 00:48 UTC, merged