kor3 site updated for demo purposes
spacesvr/muse-place pull request #76
Opened 2021-04-01 20:46 UTC by veltsonbastien

The biggest selling point for kor3 would've been the sound component, without that I would doubt our ability to close... I quickly went in and threw the sound on for everything just so that he could see it.

2021-04-01 22:04 UTC, ianyimi requested changes

2021-04-01 22:04 UTC, ianyimi commented on src/pages/kor3.tsx
> +import { NextPage } from "next";
after you make these changes can you close this pr and merge into dev? I forgot to let you know but for our dev pipeline we merge into dev first and then once we're sure everything is working there then we merge into master. its just a little insurance so we dont mess up the live site on accident

2021-04-01 22:04 UTC, ianyimi commented on src/pages/kor3.tsx
> +          {/*</mesh>*/}
This was me trying to get the text to show up on the back wall but I'll have to go into the gotham folder to get it to work. You can remove these comments though

2021-04-01 22:04 UTC, ianyimi commented on src/pages/kor3.tsx
> +const Gotham = dynamic(import("scenes/Gotham"), { ssr: false });
"scenes/Gotham/OldGotham"

2021-04-02 01:13 UTC, veltsonbastien commented on src/pages/kor3.tsx
> +    audio: true,
It is a bit chaotic, is there a way to make that better? He wants all of the sounds from each video I guess so he can hear the spatial sound as we walk around... but I could probably disable the sound on half of them and explain that it would be best to have not that many of them together? What do you think.

2021-04-02 01:13 UTC, veltsonbastien commented on src/pages/kor3.tsx
> +import { NextPage } from "next";
I will do that, thank you for letting me know!

2021-04-02 01:13 UTC, veltsonbastien commented on src/pages/kor3.tsx
> +          {/*</mesh>*/}
I will do that.

2021-04-02 01:14 UTC, veltsonbastien commented on src/pages/kor3.tsx
> +const Gotham = dynamic(import("scenes/Gotham"), { ssr: false });
For some reason I don't have the "OldGotham" I tried using that and I might have run into some errors.. I will try again though.

2021-04-12 16:44 UTC, closed without merging