Site updates
spacesvr/muse-place pull request #79
Opened 2021-04-12 08:39 UTC by ianyimi

site updates and templated sites branch in one pr

2021-04-13 03:49 UTC, alex-shortt requested changes
definitely need to get these sites on different branches next time

2021-04-13 03:49 UTC, alex-shortt commented on src/pages/balloonski.tsx
> +        audio="https://d27rt3a60hh1lx.cloudfront.net/audio/ini-bestmixever.mp3"
he wants this audio? the new default is better tbh

2021-04-13 03:49 UTC, alex-shortt commented on src/pages/kor3.tsx
> +          {/*</mesh>*/}
comments

2021-04-13 03:49 UTC, alex-shortt commented on src/pages/kor3.tsx
> +  );
unused materials

2021-04-13 03:49 UTC, alex-shortt commented on src/pages/kor3.tsx
> +    src: `${url}/6.mp4`,
5 videos?? also isn't veltson merging this file into #81

2021-04-13 03:49 UTC, alex-shortt commented on src/scenes/Alto/Homocosmico/index.tsx
> +];
move long definitions to separate file

2021-04-13 03:49 UTC, alex-shortt commented on src/scenes/Alto/Homocosmico/index.tsx
> +      <Images />
how is loading right now? especially with new spacesvr version that should have fixed a few loading issues? might want to wrap this in a `Suspense`, and even manually suspense the `Images` component.

here's an example of manually making a suspensed component delay the loading screen to finish:
```
export default function FontPreloader() {
  useAsset(
    () =>
      new Promise((res) => {
        preloadFont(
          { font: FONT_URL, characters: "abcdefghijklmnopqrstuvwxyz!.?." },
          () => {
            res(true);
          }
        );
      })
  );

  return null;
}
```

2021-04-13 03:49 UTC, alex-shortt commented on src/scenes/Alto/index.tsx
> +        {/*<Sky sunPosition={[0, 1, -1]} />*/}
comments

2021-04-13 03:49 UTC, alex-shortt commented on src/scenes/Gotham/Balloonski/index.tsx
> +const Balloonski = () => {
new version of `next` that we recently upgraded to complains about anonymous functions as components, new style is:

```
export default function Balloonski() {
...
}
```

2021-04-13 03:49 UTC, alex-shortt commented on src/scenes/Gotham/Balloonski/models/Ghost.tsx
> +  | "animation_7"
uhhh this export definitely fucked up. there's a lot of unmerged meshes, animations shouldn't be there. I think it would be worth it to re-export

2021-04-13 03:49 UTC, alex-shortt commented on src/themes/Alto/Kira.tsx
> +        <AltoModel />S{" "}
boof

2021-04-13 03:49 UTC, alex-shortt commented on src/themes/Alto/types/scroll.ts
> +  name?: string;
is this being used?

2021-04-13 03:49 UTC, alex-shortt commented on src/pages/balloonski.tsx
> +        audio="https://d27rt3a60hh1lx.cloudfront.net/audio/ini-bestmixever.mp3"
if you want to just remove the prop

2021-04-13 04:01 UTC, ianyimi commented on src/themes/Alto/types/scroll.ts
> +  name?: string;
I use it when debugging to see which scroll is which in the threejs dev tools

2021-04-13 05:33 UTC, ianyimi commented on src/pages/kor3.tsx
> +    src: `${url}/6.mp4`,
yes and I checked his branch it looks the same

2021-04-13 22:36 UTC, alex-shortt commented on src/themes/Alto/types/scroll.ts
> +  name?: string;
i would consider building the name string locally to the component, one less prop to worry about. something like

```
return <group name={`scroll-${img}`}></group>
```

it would be messy, but enough to distinguish. just a thought

2021-04-13 22:36 UTC, alex-shortt commented on src/pages/kor3.tsx
> +    src: `${url}/6.mp4`,
how does it handle 5? i imagine it's rough

2021-04-15 03:42 UTC, ianyimi commented on src/scenes/Gotham/Balloonski/models/Ghost.tsx
> +  | "animation_7"
this file wasnt even being used i deleted it

2021-04-15 04:51 UTC, alex-shortt requested changes
- the homocosmico site runs pretty slow. does it have the alto optimizations that we worked on yesterday?

2021-04-15 04:51 UTC, alex-shortt commented on src/pages/balloonski.tsx
> +        name={ARTIST.name}
add premium prop to remove "want your own?" text

2021-04-15 04:51 UTC, alex-shortt commented on src/scenes/Alto/Homocosmico/index.tsx
> +            <group position-x={1.35}>
there's a bit of z-fighting going on in the middle artworks between the image and the placard, i think you would change it here? just adding ~0.005 separation would help

2021-04-15 04:51 UTC, alex-shortt commented on src/themes/Alto/Kira.tsx
> -        <Grass />
lame

2021-04-15 04:51 UTC, alex-shortt commented on src/themes/Alto/components/Dropoff.tsx
> +    if (!limiter.isReady) return;
the use is `limiter.isReady(clock)`

2021-04-15 05:56 UTC, ianyimi commented on src/themes/Alto/components/Dropoff.tsx
> +    if (!limiter.isReady) return;
oh wtf i aint even know this i been doing it all wrong

2021-04-15 05:56 UTC, ianyimi commented on src/themes/Alto/Kira.tsx
> -        <Grass />
how dare they

2021-04-15 15:11 UTC, ianyimi commented on src/pages/balloonski.tsx
> +        name={ARTIST.name}
not sure why this doesnt say outdated, I fixed this

2021-04-15 18:07 UTC, alex-shortt reviewed
same question as on `ia-kira-alto` - did you try to optimize alto on this branch? In the model files you removed draco without changing the model url, which probably won't work. Take a look at the `as/ia-alto-optimize` branch, would recommend merging that in.

also can you list all the new sites on the pr description

2021-04-16 02:49 UTC, alex-shortt commented
scratch the updates comment, so just list the new sites in the main pr comment

2021-04-16 03:18 UTC, alex-shortt approved these changes

2021-04-16 03:18 UTC, merged