Vb veltson create branch, and kor3 site
spacesvr/muse-place pull request #81
Opened 2021-04-12 22:39 UTC by veltsonbastien

Since lots of changes happened, I think kor3's demo site still needs to get put up

2021-04-12 22:50 UTC, alex-shortt requested changes

2021-04-12 22:50 UTC, alex-shortt commented on src/pages/kor3.tsx
> +          {/*</mesh>*/}
remove comment

2021-04-12 22:50 UTC, alex-shortt commented on src/pages/kor3.tsx
> +        <group position={[0, 0, 0]}>
don't need `position={[0, 0, 0]}`

2021-04-12 22:50 UTC, alex-shortt commented on src/pages/kor3.tsx
> +  );
pretty sure this is unused, feel free to delete

2021-04-14 13:41 UTC, alex-shortt approved these changes

2021-04-14 14:44 UTC, alex-shortt requested changes
sorry for accepting, just realized the props are wrong

2021-04-14 14:44 UTC, alex-shortt commented on src/pages/kor3.tsx
> +        floorColor="black"
these props are not offered by Gotham. do you mean OldGotham?

2021-04-14 19:39 UTC, veltsonbastien commented on src/pages/kor3.tsx
> +        floorColor="black"
Probably? I can change it to that

2021-04-15 02:13 UTC, alex-shortt approved these changes

2021-04-15 02:13 UTC, merged