Ia brendannorth
spacesvr/muse-place pull request #87
Opened 2021-04-22 14:04 UTC by ianyimi

unfortunately this also has the balloonski shop changes I made as well bc i based this branch off that one

2021-04-25 02:40 UTC, alex-shortt requested changes
- dm'd you shopify info
- don't share files across scenes folders, you should copy and paste them or abstract them sufficiently to the themes folder or spacesvr

2021-04-25 02:40 UTC, alex-shortt commented on src/themes/components/Link.tsx
> +    return <></>;
don't need blank prop

2021-04-25 02:40 UTC, alex-shortt commented on src/themes/components/Artwork.tsx
> +          blank={piece.blank}
why not return 
```
!piece.blank &&  <Link
          position={linkPositions[i].p}
          rotY={linkPositions[i].r}
          audio={piece.audio}
          link={piece.link}
          size={piece.size}
          src={piece.src}
/>
```

no need to add another prop to link

2021-04-25 02:40 UTC, alex-shortt commented on src/themes/Alto/index.tsx
> +      <Scrolls count={scrollCount} setCount={setScrollCount} />{" "}
extra {" "}

2021-04-25 02:40 UTC, alex-shortt commented on src/themes/Alto/components/Scrolls/Scroll.tsx
> +            {" "}
extra {" "}

2021-04-25 02:40 UTC, alex-shortt commented on src/scenes/Silks/modifiers/Spinning.tsx
> +  const limiter = useLimiter(45);
i believe we export this from `spacesvr` now

2021-04-25 02:40 UTC, alex-shortt commented on src/scenes/Gotham/Balloonski/components/Shop/Kiosk.tsx
> +import { ShopContext } from "../../../../Silks";
you need to clone the files to keep them separate from the silks files until we can abstract it enough to `spacesvr` or to the `themes/components` folder

2021-04-25 02:40 UTC, alex-shortt commented on src/scenes/Gotham/Balloonski/index.tsx
> +  // });
we got the info, i'll dm it to you

2021-04-25 02:40 UTC, alex-shortt commented on src/scenes/Gotham/Balloonski/models/Gator.tsx
> +  "https://d27rt3a60hh1lx.cloudfront.net/models/gator-1618894625/gator.glb.gz\n";
\n

2021-04-25 02:40 UTC, alex-shortt commented on src/scenes/Silks/components/Cart/components/Control.tsx
> +    cart && cart?.count > 0
the `cart && ` should check whether cart is undefined, so you shouldn't need the `?` after

2021-04-25 02:40 UTC, alex-shortt commented on src/scenes/Silks/components/Cart/index.tsx
> +  }, [incr, cart?.count]);
how come all the `?` pretty sure cart is always defined

2021-05-06 04:12 UTC, alex-shortt requested changes

2021-05-06 04:12 UTC, alex-shortt commented on src/scenes/Gotham/Balloonski/index.tsx
> +        {/*<Renderer />*/}
remove renderer

2021-05-06 04:12 UTC, alex-shortt commented on src/scenes/Gotham/Balloonski/models/Desk.tsx
> +  // }
would recommend using `useBox` from `@react-three/cannon`

2021-05-06 04:12 UTC, alex-shortt commented on src/themes/components/Artwork.tsx
> +              key={i}
sorry why is this blank prop here? feels unnecessary

2021-05-06 07:12 UTC, ianyimi commented on src/themes/components/Artwork.tsx
> +              key={i}
it's just so I didn't get that react warning in the console

2021-05-11 00:39 UTC, alex-shortt approved these changes

2021-05-11 00:41 UTC, merged